Repository googleapis/python-securitycenter, pull requests merged in 2020-07, with the labels that each got.

#40 chore: update protobuf and gapic-generator-csharp versions.
  google/cloud/securitycenter_v1/proto/asset_pb2.py
  google/cloud/securitycenter_v1/proto/finding_pb2.py
  google/cloud/securitycenter_v1/proto/notification_config_pb2.py
  google/cloud/securitycenter_v1/proto/notification_message_pb2.py
  google/cloud/securitycenter_v1/proto/organization_settings_pb2.py
  google/cloud/securitycenter_v1/proto/resource_pb2.py
  google/cloud/securitycenter_v1/proto/run_asset_discovery_response_pb2.py
  google/cloud/securitycenter_v1/proto/security_marks_pb2.py
  google/cloud/securitycenter_v1/proto/securitycenter_service_pb2.py
  google/cloud/securitycenter_v1/proto/source_pb2.py
  google/cloud/securitycenter_v1beta1/proto/asset_pb2.py
  google/cloud/securitycenter_v1beta1/proto/finding_pb2.py
  google/cloud/securitycenter_v1beta1/proto/organization_settings_pb2.py
  google/cloud/securitycenter_v1beta1/proto/run_asset_discovery_response_pb2.py
  google/cloud/securitycenter_v1beta1/proto/security_marks_pb2.py
  google/cloud/securitycenter_v1beta1/proto/securitycenter_service_pb2.py
  google/cloud/securitycenter_v1beta1/proto/source_pb2.py
  google/cloud/securitycenter_v1p1beta1/proto/asset_pb2.py
  google/cloud/securitycenter_v1p1beta1/proto/finding_pb2.py
  google/cloud/securitycenter_v1p1beta1/proto/notification_config_pb2.py
  google/cloud/securitycenter_v1p1beta1/proto/notification_message_pb2.py
  google/cloud/securitycenter_v1p1beta1/proto/organization_settings_pb2.py
  google/cloud/securitycenter_v1p1beta1/proto/resource_pb2.py
  google/cloud/securitycenter_v1p1beta1/proto/run_asset_discovery_response_pb2.py
  google/cloud/securitycenter_v1p1beta1/proto/security_marks_pb2.py
  google/cloud/securitycenter_v1p1beta1/proto/securitycenter_service_pb2.py
  google/cloud/securitycenter_v1p1beta1/proto/source_pb2.py
  synth.metadata
Labels: cla: yes, context: full

#41 chore(samples): move samples and use standard templates for testing
  .github/CODEOWNERS
  noxfile.py
  samples/AUTHORING_GUIDE.md
  samples/CONTRIBUTING.md
  samples/snippets/noxfile.py
  samples/snippets/noxfile_config.py
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
  samples/snippets/snippets_findings.py
  samples/snippets/snippets_findings_test.py
  samples/snippets/snippets_list_assets.py
  samples/snippets/snippets_list_assets_test.py
  samples/snippets/snippets_notification_configs.py
  samples/snippets/snippets_notification_receiver.py
  samples/snippets/snippets_notification_test.py
  samples/snippets/snippets_orgs.py
  samples/snippets/snippets_orgs_test.py
  samples/snippets/snippets_security_marks.py
  samples/snippets/snippets_security_marks_test.py
  setup.py
  synth.metadata
  synth.py
Labels: cla: yes

#46 chore: remove samples in `docs`
  docs/requirements.txt
  docs/snippets_findings.py
  docs/snippets_list_assets.py
  docs/snippets_notification_configs.py
  docs/snippets_notification_receiver.py
  docs/snippets_notification_test.py
  docs/snippets_orgs.py
  docs/snippets_security_marks.py
Labels: cla: yes

#39 docs: Update Security Command Center UpdateNotificationConfig sample, adding filter to mutable field
  samples/snippets/snippets_notification_configs.py
Labels: automerge, cla: yes
