Repository googleapis/python-securitycenter, pull requests merged in 2021-02, with the labels that each got.

#97 chore: update templates
  LICENSE
  docs/_static/custom.css
  securitycenter-v1beta1-py.tar.gz
  synth.metadata
Labels: api: securitycenter, automerge, cla: yes, context: partial

#94 chore: add constraints file
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
Labels: api: securitycenter, automerge, cla: yes

#104 docs: standardize new tag with existing tags from other languages
  samples/snippets/snippets_findings.py
  samples/snippets/snippets_list_assets.py
  samples/snippets/snippets_orgs.py
  samples/snippets/snippets_security_marks.py
Labels: api: securitycenter, automerge, cla: yes

#106 docs: Fix conflict tag introduced in PR 104
  samples/snippets/snippets_security_marks.py
Labels: api: securitycenter, cla: yes
