Repository googleapis/python-securitycenter, pull requests merged in 2021-03, with the labels that each got.

#80 chore: require samples checks
  .github/sync-repo-settings.yaml
Labels: api: securitycenter, automerge, cla: yes, samples

#111 chore: cleanup synth.py
  synth.py
Labels: api: securitycenter, automerge, cla: yes

#118 build(python): update docfx job to use new plugin
  noxfile.py
  synth.metadata
Labels: api: securitycenter, cla: yes, context: full
